"""empty message

Revision ID: 83d262d144de
Revises: a5cffa318ac2
Create Date: 2025-04-11 20:13:50.323985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d262d144de'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('char_id', sa.Integer(), nullable=False),
    sa.Column('char_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('race', sa.String(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('allegiance', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('char_id'),
    sa.UniqueConstraint('char_name')
    )
    op.create_table('planets',
    sa.Column('pla_id', sa.Integer(), nullable=False),
    sa.Column('pla_name', sa.String(), nullable=False),
    sa.Column('system', sa.String(), nullable=False),
    sa.Column('Moons', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pla_id'),
    sa.UniqueConstraint('pla_name')
    )
    op.create_table('starships',
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('ship_name', sa.String(), nullable=False),
    sa.Column('designer', sa.String(), nullable=False),
    sa.Column('affiliation', sa.String(), nullable=False),
    sa.Column('year_introduced', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ship_id'),
    sa.UniqueConstraint('ship_name')
    )
    op.create_table('character_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.char_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.pla_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starship_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.ship_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=25), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=25), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    op.drop_table('starship_favorites')
    op.drop_table('planet_favorites')
    op.drop_table('character_favorites')
    op.drop_table('starships')
    op.drop_table('planets')
    op.drop_table('characters')
    # ### end Alembic commands ###
