"""empty message

Revision ID: 94616d19ff55
Revises: 83d262d144de
Create Date: 2025-04-15 15:47:04.706788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94616d19ff55'
down_revision = '83d262d144de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moons', sa.Integer(), nullable=False))
        batch_op.drop_column('Moons')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Moons', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('moons')

    # ### end Alembic commands ###
